[project]
name = "pyseekdb"
version = "1.0.0.b4"
description = "A unified Python client for seekdb that supports embedded, server, and OceanBase."
readme = "README.md"
license = { text = "Apache-2.0" }
authors = [{ name = "OceanBase", email = "open_oceanbase@oceanbase.com" }]
requires-python = ">=3.11,<3.14"
classifiers = [
    "Development Status :: 4 - Beta",
]
dependencies = [
    "pymysql>=1.1.1",
    "pylibseekdb; sys_platform == \"linux\"",
    "onnxruntime>=1.19.0",
    "tokenizers>=0.15.0",
    "httpx",
    "tqdm",
    "tenacity",
    "numpy>=1.26",
]

[project.urls]
Homepage = "https://github.com/oceanbase/pyseekdb/"
Repository = "https://github.com/oceanbase/pyseekdb/"
"Bug Tracker" = "https://github.com/oceanbase/pyseekdb/issues"

[dependency-groups]
dev = [
    "pytest>=8.2.2",
    "pylint>=3.2.7",
    "sphinx>=8.2.3",
    "sphinx-rtd-theme>=3.0.2",
    "myst-parser>=4.0.1",
    "prek>=0.2.17",
    "ruff>=0.11.5",
]

[tool.uv.workspace]
members = ["demo/rag"]

[tool.pdm.build]
source-includes = ["docs/", "examples/", "tests/"]
excludes = ["docs/_build/", "tests/seekdb.db/"]

[tool.pytest.ini_options]
log_level = "INFO"

[tool.ruff]
target-version = "py311"
line-length = 120
fix = true

[tool.ruff.lint]
select = [
    # flake8-2020
    "YTT",
    # flake8-bandit
    "S",
    # flake8-bugbear
    "B",
    # flake8-builtins
    "A",
    # flake8-comprehensions
    "C4",
    # flake8-debugger
    "T10",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # mccabe
    "C90",
    # pycodestyle
    "E", "W",
    # pyflakes
    "F",
    # pygrep-hooks
    "PGH",
    # pyupgrade
    "UP",
    # ruff
    "RUF",
    # tryceratops
    "TRY",
]
ignore = [
    # LineTooLong
    "E501",
    # DoNotAssignLambda
    "E731",
    # Long exception message
    "TRY003",
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
